---

- name: Ensure dbus is installed
  apt:
    pkg: dbus

- name: Downloading Node Exporter Release
  get_url:
    url:  "{{ prometheus_node_exporter_download }}"
    dest: "{{ prometheus_node_exporter_source_dir }}/"

- name: Extracting Prometheus Node Exporter
  unarchive:
    src:  "{{ prometheus_node_exporter_source_dir }}/{{ prometheus_node_exporter_download|basename }}"
    dest: "{{ prometheus_node_exporter_install_dir }}"
    copy: false
  args:
    creates: "{{ prometheus_node_exporter_install_dir }}/node_exporter-{{ prometheus_node_exporter_version }}.linux-amd64/node_exporter"

- name: Creating Symlink For Prometheus ({{ prometheus_node_exporter_install_dir }}/node_exporter)
  file:
    src:   "{{ prometheus_node_exporter_install_dir }}/node_exporter-{{ prometheus_node_exporter_version }}.linux-amd64"
    dest:  "{{ prometheus_node_exporter_install_dir }}/node_exporter"
    state: "link"

