---

- name: Create directories
  file:
    path:  "{{ drone_docker_home }}/{{ item.path }}"
    mode:  "{{ item.mode }}"
    state: directory
  with_filetree: ../templates/
  when: item.state == 'directory'

- name: Template files
  template:
    src:   "{{ item.src }}"
    dest:  "{{ drone_docker_home }}/{{ item.path }}"
    mode:  "{{ item.mode }}"
  with_filetree: ../templates/
  when: item.state == 'file'

- name: docker compose drone
  docker_service:
    project_src: "{{ drone_docker_home }}"

- meta: flush_handlers

- name: validate for drone is listening
  wait_for:
    port:    443
    delay:   3
    timeout: 30

