---

- hosts: "tag_{{ component }}"
  become: True
  gather_facts: True

  vars:
    common_storage:
      - device: /dev/sdb
        mount:  "{{ gocd_docker_home }}"
        opts:   noatime
        owner:  root
        group:  root
        # mode:   711

  roles:
    - common-storage
    - gocd

